name: Release Please

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release

      - name: Assign PR to repository owner
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        run: gh pr edit ${{ fromJSON(steps.release.outputs.pr).number }} --add-assignee ${{ github.repository_owner }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

